uploads = []
outputs = []

[[generated]]
id = "hz9l3DfGFAfiFm0YUwA10"
uri = "file://artifacts/vtm-companion/public/images/brujah.png"
type = "image"
title = "Brujah clan image"

[[generated]]
id = "7mBue74dhk3A2E5MOLRfh"
uri = "file://artifacts/vtm-companion/public/images/ventrue.png"
type = "image"
title = "Ventrue clan image"

[[generated]]
id = "1EJsukWRTob_8xTiTtGn5"
uri = "file://artifacts/vtm-companion/public/images/tremere.png"
type = "image"
title = "Tremere clan image"

[[generated]]
id = "JtcLVvTsnKzLie3-EVQ47"
uri = "file://artifacts/vtm-companion/public/images/nosferatu.png"
type = "image"
title = "Nosferatu clan image"

[[generated]]
id = "YRu0KvXRoDIyJPjqKxzug"
uri = "file://artifacts/vtm-companion/public/images/toreador.png"
type = "image"
title = "Toreador clan image"

[[generated]]
id = "BLu5VnJpFqdNJm8AOmeoz"
uri = "file://artifacts/vtm-companion/public/images/malkavian.png"
type = "image"
title = "Malkavian clan image"

[[generated]]
id = "pSfxiZDglSOaYvOF7upHC"
uri = "file://artifacts/vtm-companion/public/images/gangrel.png"
type = "image"
title = "Gangrel clan image"

[[generated]]
id = "mDumqRJev8_Fe_wTOgRG1"
uri = "file://artifacts/vtm-companion/public/images/banu-haquim.png"
type = "image"
title = "banu haquim clan portrait"

[[generated]]
id = "NOpcivfCRo42NWh8ZIYRN"
uri = "file://artifacts/vtm-companion/public/images/hecata.png"
type = "image"
title = "hecata clan portrait"

[[generated]]
id = "AWZu_PwMTJ1qnjEJxJQTo"
uri = "file://artifacts/vtm-companion/public/images/lasombra.png"
type = "image"
title = "lasombra clan portrait"

[[generated]]
id = "3LLn3HgtI4Qgy9KXzc_Dn"
uri = "file://artifacts/vtm-companion/public/images/ministry.png"
type = "image"
title = "ministry clan portrait"

[[generated]]
id = "lVGu9-XfthqXTmRVziuun"
uri = "file://artifacts/vtm-companion/public/images/ravnos.png"
type = "image"
title = "ravnos clan portrait"

[[generated]]
id = "jHvWhHnp_dmyeODMEzJDw"
uri = "file://artifacts/vtm-companion/public/images/salubri.png"
type = "image"
title = "salubri clan portrait"
